-- Expand NotificationType for notification center v1

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FORM_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ATTENDANCE_ALERT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'LOW_GRADE_ALERT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'NEW_PUBLISHED_GRADE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ADMIN_BROADCAST';
