export const AUDIT_RETENTION_DAYS = 365;
export const AUDIT_RETENTION_RUN_INTERVAL_MS = 60 * 60 * 1000;
export const AUDIT_PURGE_CONFIRMATION_TEXT = 'PURGE AUDIT LOGS';
export const AUDIT_EXPORT_MAX_ROWS = 10000;
